[/Script/EngineSettings.GameMapsSettings]
; Set EditorStartupMap / GameDefaultMap / GlobalDefaultGameMode in editor once test map + game mode exist.

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12

[OnlineSubsystem]
DefaultPlatformService=Null

[/Script/Engine.Player]
ConfiguredInternetSpeed=100000
ConfiguredLanSpeed=100000

[/Script/OnlineSubsystemUtils.IpNetDriver]
MaxClientRate=100000
MaxInternetClientRate=100000
NetServerMaxTickRate=60
